data=[
    {"Name":"Ram","Sale":5600,"city":"Jaipur"},
    {"Name":"Shyam","Sale":5600,"city":"Jaipur"},
    {"Name":"Kapil","Sale":5600,"city":"Jaipur"},
    {"Name":"Pardeep","Sale":5600,"city":"Jaipur"},
    {"Name":"Jakir","Sale":5600,"city":"Jaipur"},
];
data.map((singledata)=>{
    if(singledata.Name=="Ram")
        console.log(singledata.Sale);
    });
